# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitmap < Formula
  desc "TUI for managing multiple git repositories"
  homepage "https://github.com/yhkl-dev/gitmap"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yhkl-dev/gitmap/releases/download/v0.1.7/gitmap_0.1.7_darwin_amd64.tar.gz"
      sha256 "24855994a2caf4ae3f48c5a31143dbf6fa29d4099aacdf22d75b9cd5acbb0cf9"

      define_method(:install) do
        bin.install "gitmap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yhkl-dev/gitmap/releases/download/v0.1.7/gitmap_0.1.7_darwin_arm64.tar.gz"
      sha256 "863ee887da89d1a363166c4d114bd077e6aa24ccb6e65c3f8f18366339154ff9"

      define_method(:install) do
        bin.install "gitmap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yhkl-dev/gitmap/releases/download/v0.1.7/gitmap_0.1.7_linux_amd64.tar.gz"
      sha256 "785e3f9af4d871e8bf9df53ddc9c6d9246d1d406f76c2bd018b5e95747e7cc50"
      define_method(:install) do
        bin.install "gitmap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yhkl-dev/gitmap/releases/download/v0.1.7/gitmap_0.1.7_linux_arm64.tar.gz"
      sha256 "d138eb59343a612b74cbcf1bfb65936b183db5ce8548396de5ee786b3f07819b"
      define_method(:install) do
        bin.install "gitmap"
      end
    end
  end

  test do
    system "#{bin}/gitmap --help"
  end
end
